bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  owner: ${BOT_OWNER}
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webapp
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:file:.env[.properties]