bot:
  username: akmsobesbot
  token: 7627408434:AAGOqQ_5Df2fb-f63RmQgcSCeJke63UBJao
  owner: 928437440
spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect